name: Push the analyzer to analyzer branch
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn build

      # push folder
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: analyzer # The branch name where you want to push the assets
          FOLDER: analyzer # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
